server:
  port: 9527
spring:
  application:
    name: myspringcloudproject-gateway  #服务名
  cloud:
    gateway:
      routes:
        - id: order_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8080
          uri: lb://myspringcloudproject-order
          predicates:
            - Path=/consumer/payment/get/** # 断言，路径相匹配的进行路由
            - After=2022-11-24T18:01:34.929+08:00[Asia/Shanghai]  #断言在当前时间之后才可以访问,亚洲以上海为主要时区

        - id: order_route01 # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8080
          uri: lb://myspringcloudproject-order
          predicates:
            - Path=/consumer/payment/create/** # 断言，路径相匹配的进行路由
            - After=2022-11-24T18:01:34.929+08:00[Asia/Shanghai]  #断言在当前时间之后才可以访问,亚洲以上海为主要时区

        - id: payment_route
          #uri: http://localhost:8001
          uri: lb://myspringcloudproject-payment
          predicates:
            Path=/payment/get/** #断言,路径相匹配的进行路由
#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机配置
      #defaultZone: http://localhost:7001/eureka
      #集群配置,集群的话得写具体的服务器地址,localhost不行
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    instance:
      #服务名称修改
      instance-id: order80
      #访问路径可以显示ip地址
      prefer-ip-address: true